#!/bin/sh
set -e
# Automatically added by dh_installdeb/12.1.1
dpkg-maintscript-helper rm_conffile /etc/bash_completion.d/devscripts.chdist 2.15.5\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/bash_completion.d/devscripts.debchange 2.15.5\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/bash_completion.d/devscripts.debsign 2.15.5\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/bash_completion.d/devscripts.pkgnames 2.15.5\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/bash_completion.d/devscripts.uupdate 2.15.5\~ -- "$@"
# End automatically added section
